"""Fix model relationships

Revision ID: b95b920993f6
Revises: 347b13dd8a44
Create Date: 2025-10-14 17:15:15.497557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95b920993f6'
down_revision = '347b13dd8a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
